//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BASIC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace tf9ik {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class BASICLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		LETTER=10, DIGIT=11, WS=12;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"LETTER", "DIGIT", "WS"
	};


	public BASICLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public BASICLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "','", "'As'", "'='", "'Dim'", "'Public'", "'Private'", "'Double'", 
		"'Integer'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "LETTER", 
		"DIGIT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BASIC.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static BASICLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,12,79,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,1,0,1,0,1,1,1,1,1,1,1,2,1,
		2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,
		8,1,8,1,9,1,9,1,10,1,10,1,11,4,11,74,8,11,11,11,12,11,75,1,11,1,11,0,0,
		12,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,1,0,3,3,0,
		65,90,95,95,97,122,1,0,48,57,3,0,9,10,13,13,32,32,79,0,1,1,0,0,0,0,3,1,
		0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,
		15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,1,25,1,
		0,0,0,3,27,1,0,0,0,5,30,1,0,0,0,7,32,1,0,0,0,9,36,1,0,0,0,11,43,1,0,0,
		0,13,51,1,0,0,0,15,58,1,0,0,0,17,66,1,0,0,0,19,68,1,0,0,0,21,70,1,0,0,
		0,23,73,1,0,0,0,25,26,5,44,0,0,26,2,1,0,0,0,27,28,5,65,0,0,28,29,5,115,
		0,0,29,4,1,0,0,0,30,31,5,61,0,0,31,6,1,0,0,0,32,33,5,68,0,0,33,34,5,105,
		0,0,34,35,5,109,0,0,35,8,1,0,0,0,36,37,5,80,0,0,37,38,5,117,0,0,38,39,
		5,98,0,0,39,40,5,108,0,0,40,41,5,105,0,0,41,42,5,99,0,0,42,10,1,0,0,0,
		43,44,5,80,0,0,44,45,5,114,0,0,45,46,5,105,0,0,46,47,5,118,0,0,47,48,5,
		97,0,0,48,49,5,116,0,0,49,50,5,101,0,0,50,12,1,0,0,0,51,52,5,68,0,0,52,
		53,5,111,0,0,53,54,5,117,0,0,54,55,5,98,0,0,55,56,5,108,0,0,56,57,5,101,
		0,0,57,14,1,0,0,0,58,59,5,73,0,0,59,60,5,110,0,0,60,61,5,116,0,0,61,62,
		5,101,0,0,62,63,5,103,0,0,63,64,5,101,0,0,64,65,5,114,0,0,65,16,1,0,0,
		0,66,67,5,46,0,0,67,18,1,0,0,0,68,69,7,0,0,0,69,20,1,0,0,0,70,71,7,1,0,
		0,71,22,1,0,0,0,72,74,7,2,0,0,73,72,1,0,0,0,74,75,1,0,0,0,75,73,1,0,0,
		0,75,76,1,0,0,0,76,77,1,0,0,0,77,78,6,11,0,0,78,24,1,0,0,0,2,0,75,1,6,
		0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace tf9ik
