//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BASIC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace tf9ik {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BASICParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBASICListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BASICParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BASICParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] BASICParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] BASICParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.declarationWithoutMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationWithoutMod([NotNull] BASICParser.DeclarationWithoutModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.declarationWithoutMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationWithoutMod([NotNull] BASICParser.DeclarationWithoutModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] BASICParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] BASICParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] BASICParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] BASICParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataType([NotNull] BASICParser.DataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataType([NotNull] BASICParser.DataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BASICParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] BASICParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BASICParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] BASICParser.ConstantContext context);
}
} // namespace tf9ik
